# Generated by Django 5.2.5 on 2025-08-29 00:50

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("leader", "Leader"),
                            ("worker", "Worker"),
                            ("n_member", "Normal Member"),
                            ("seeker", "Seeker"),
                            ("newcomer", "New-comer"),
                            ("visitor", "Visitor"),
                        ],
                        default="n_member",
                        max_length=15,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="data_system.departement",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departement",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leading_departments",
                to="data_system.member",
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sunday_service", "Sunday Service"),
                            ("national_program", "National Program"),
                            ("special_program", "Special program"),
                        ],
                        default="sunday_service",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_system.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("leader", "Leader"),
                            ("worker", "Worker"),
                            ("n_member", "Normal Member"),
                            ("seeker", "Seeker"),
                            ("newcomer", "New-comer"),
                            ("visitor", "Visitor"),
                        ],
                        default="n_member",
                        max_length=10,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("leader", "Leader"),
                            ("worker", "Worker"),
                            ("n_member", "Normal Member"),
                            ("seeker", "Seeker"),
                            ("newcomer", "New-comer"),
                            ("visitor", "Visitor"),
                        ],
                        default="n_member",
                        max_length=10,
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_system.member",
                    ),
                ),
            ],
        ),
    ]
