# Generated by Django 5.2.5 on 2025-08-27 19:48

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="name",
        ),
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="member",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="status",
            field=models.CharField(
                choices=[
                    ("pastor", "Pastor"),
                    ("elder", "Elder"),
                    ("leader", "Leader"),
                    ("worker", "Worker"),
                    ("n_member", "Normal Member"),
                    ("seeker", "Seeker"),
                    ("newcomer", "New-comer"),
                    ("visitor", "Visitor"),
                ],
                default="n_member",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sunday_service", "Sunday Service"),
                            ("national_program", "National Program"),
                            ("special_program", "Special program"),
                        ],
                        default="sunday_service",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("present", "Present"), ("absent", "Absent")],
                        default="present",
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_system.member",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leading_departments",
                        to="data_system.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="departement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="data_system.departement",
            ),
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("leader", "Leader"),
                            ("worker", "Worker"),
                            ("n_member", "Normal Member"),
                            ("seeker", "Seeker"),
                            ("newcomer", "New-comer"),
                            ("visitor", "Visitor"),
                        ],
                        default="n_member",
                        max_length=10,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("pastor", "Pastor"),
                            ("elder", "Elder"),
                            ("leader", "Leader"),
                            ("worker", "Worker"),
                            ("n_member", "Normal Member"),
                            ("seeker", "Seeker"),
                            ("newcomer", "New-comer"),
                            ("visitor", "Visitor"),
                        ],
                        default="n_member",
                        max_length=10,
                    ),
                ),
                ("date_changed", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_system.member",
                    ),
                ),
            ],
        ),
    ]
