# Generated by Django 5.2.5 on 2025-08-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="name",
            field=models.CharField(
                choices=[
                    ("choir", "Choir"),
                    ("minister_sherpherd", "Minister Sherpherd"),
                    ("media", "Media"),
                    ("organisatio_usher", "Organisation & Usher"),
                    ("outreach_visitation", "Outreach & Visitation"),
                    ("kitchen", "Kitchen"),
                    ("drama_team", "Drama Team"),
                ],
                default="choir",
                max_length=225,
            ),
        ),
    ]
